src/feed: fetch `published_at` as type `String`
sqlx seems to choke on RFC 2822 datetime values, for example:

```
Error: error occurred while decoding column 0: invalid datetime: Mon, 12
Aug 2024 12:00:00 +0000

Caused by:
    invalid datetime: Mon, 12 Aug 2024 12:00:00 +0000
```

I'm not sure yet if this is by design or a bug. For the time being,
fetch `published_at` as type `String`.